---
#:verbose: false
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:retry: false
#staging:
#  :concurrency: 10
#production:
#  :concurrency: 20
:queues:
  - default
  - mailers
